name: Initialize Intended Release
on:
  workflow_dispatch:
    inputs:
      type:
        description: "Release Type [major|minor|patch]"
        required: true

jobs:
  initializeIntendedRelease:
    name: "Initialize Intended Release"
    runs-on: ubuntu-latest
    steps:
      - uses: jonsnyder/project-card-release-automation/initialize-card@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          releaseType: ${{ github.event.inputs.type }}
          projectNumber: 7